#include "image_metadata.h"
#include "dem_event_adapter.h"
#include "image_validator.h"
#include "stm32f1xx_hal.h"
#include <stddef.h>
#include <string.h>

typedef char V2Size[(sizeof(ImageMetadata_RecordType)==64U)?1:-1];
typedef char V2CrcOffset[(offsetof(ImageMetadata_RecordType,metadata_crc32)==56U)?1:-1];
typedef char V2MarkerOffset[(offsetof(ImageMetadata_RecordType,commit_marker)==60U)?1:-1];
typedef struct { uint32_t magic; uint16_t format_version,record_size; uint32_t sequence,update_state,image_base,image_size,image_crc32; uint8_t software_version[4],slot_id,flags; uint16_t reserved16; uint32_t reserved32[5],metadata_crc32; uint16_t commit_marker,padding; } V1Record;
typedef char V1Size[(sizeof(V1Record)==64U)?1:-1];
typedef struct { uint8_t bytes[64]; uint32_t page,sequence; uint16_t format; bool erased,valid; } Candidate;

static bool IsPage(uint32_t p){return p==IMAGE_METADATA_PAGE_A_ADDRESS||p==IMAGE_METADATA_PAGE_B_ADDRESS;}
static bool IsErased(uint32_t p){uint32_t i;if(!IsPage(p))return false;for(i=0;i<IMAGE_METADATA_PAGE_SIZE;i+=2U)if(*(volatile const uint16_t*)(p+i)!=0xFFFFU)return false;return true;}
bool ImageMetadata_IsSequenceNewer(uint32_t c,uint32_t r){return c!=r&&(int32_t)(c-r)>0;}
uint8_t ImageMetadata_GetSlotState(const ImageMetadata_RecordType*r,uint8_t s){return s==IMAGE_SLOT_A_ID?r->slot_a_state:s==IMAGE_SLOT_B_ID?r->slot_b_state:0xFFU;}
uint32_t ImageMetadata_GetSlotSize(const ImageMetadata_RecordType*r,uint8_t s){return s==IMAGE_SLOT_A_ID?r->slot_a_image_size:s==IMAGE_SLOT_B_ID?r->slot_b_image_size:0U;}
uint32_t ImageMetadata_GetSlotCrc(const ImageMetadata_RecordType*r,uint8_t s){return s==IMAGE_SLOT_A_ID?r->slot_a_crc32:s==IMAGE_SLOT_B_ID?r->slot_b_crc32:0U;}
const uint8_t*ImageMetadata_GetSlotVersion(const ImageMetadata_RecordType*r,uint8_t s){return s==IMAGE_SLOT_A_ID?r->slot_a_version:s==IMAGE_SLOT_B_ID?r->slot_b_version:NULL;}
static bool V1Valid(const V1Record*r){uint32_t i;if(r->magic!=IMAGE_METADATA_MAGIC||r->format_version!=1U||r->record_size!=64U||r->commit_marker!=IMAGE_METADATA_COMMIT_MARKER||r->padding!=0xFFFFU||r->metadata_crc32!=ImageValidator_CalculateCrc32((const uint8_t*)r,56U)||r->image_base!=IMAGE_SLOT_A_BASE||!ImageValidator_IsImageRangeValidForSlot(IMAGE_SLOT_A_ID,r->image_base,r->image_size)||r->slot_id!=0U||r->flags!=0U||r->reserved16!=0U)return false;if(r->update_state<1U||r->update_state>3U)return false;for(i=0;i<5U;i++)if(r->reserved32[i]!=0U)return false;return true;}
static bool SlotValid(const ImageMetadata_RecordType*r,uint8_t s){uint8_t st=ImageMetadata_GetSlotState(r,s);uint32_t z=ImageMetadata_GetSlotSize(r,s);if(st>IMAGE_SLOT_STATE_INVALID)return false;if(st==IMAGE_SLOT_STATE_EMPTY)return z==0U;if(z==0U)return st==IMAGE_SLOT_STATE_INVALID;return ImageValidator_IsImageRangeValidForSlot(s,ImageLayout_GetSlotBase(s),z);}
static bool V2Valid(const ImageMetadata_RecordType*r){bool c=(r->confirmed_slot==IMAGE_SLOT_NONE)||(ImageLayout_IsSlotId(r->confirmed_slot)&&ImageMetadata_GetSlotState(r,r->confirmed_slot)==IMAGE_SLOT_STATE_CONFIRMED);bool p=(r->pending_slot==IMAGE_SLOT_NONE)||(ImageLayout_IsSlotId(r->pending_slot)&&r->pending_slot!=r->confirmed_slot&&ImageMetadata_GetSlotState(r,r->pending_slot)==IMAGE_SLOT_STATE_PENDING);return r->magic==IMAGE_METADATA_MAGIC&&r->format_version==2U&&r->record_size==64U&&r->commit_marker==IMAGE_METADATA_COMMIT_MARKER&&r->padding==0xFFFFU&&r->metadata_crc32==ImageValidator_CalculateCrc32((const uint8_t*)r,56U)&&SlotValid(r,IMAGE_SLOT_A_ID)&&SlotValid(r,IMAGE_SLOT_B_ID)&&c&&p&&(r->active_slot==IMAGE_SLOT_NONE||ImageLayout_IsSlotId(r->active_slot))&&(r->last_boot_slot==IMAGE_SLOT_NONE||ImageLayout_IsSlotId(r->last_boot_slot))&&r->boot_attempt_count<=r->max_boot_attempts&&r->max_boot_attempts==3U&&r->rollback_reason<=IMAGE_ROLLBACK_CONFIRMED_IMAGE_INVALID&&r->flags==0U&&r->reserved16==0U&&r->reserved32[0]==0U&&r->reserved32[1]==0U;}
static void Read(uint32_t p,Candidate*c){const V1Record*v1;const ImageMetadata_RecordType*v2;c->page=p;c->erased=IsErased(p);memcpy(c->bytes,(const void*)p,64U);v1=(const V1Record*)c->bytes;v2=(const ImageMetadata_RecordType*)c->bytes;c->format=v1->format_version;c->sequence=v1->sequence;c->valid=!c->erased&&((c->format==1U&&V1Valid(v1))||(c->format==2U&&V2Valid(v2)));}
void ImageMetadata_Scan(ImageMetadata_ScanResultType*out){Candidate a,b;const Candidate*s=NULL;if(!out)return;memset(out,0,sizeof(*out));Read(IMAGE_METADATA_PAGE_A_ADDRESS,&a);Read(IMAGE_METADATA_PAGE_B_ADDRESS,&b);if(a.valid&&b.valid)s=ImageMetadata_IsSequenceNewer(b.sequence,a.sequence)?&b:&a;else if(a.valid)s=&a;else if(b.valid)s=&b;if(!s){out->state=(a.erased&&b.erased)?IMAGE_METADATA_ABSENT_LEGACY:IMAGE_METADATA_CORRUPT;return;}out->active_page_address=s->page;if(s->format==2U){out->state=IMAGE_METADATA_SCAN_V2_RECORD;memcpy(&out->record,s->bytes,64U);}else{const V1Record*v=(const V1Record*)s->bytes;out->state=IMAGE_METADATA_SCAN_V1_RECORD;out->legacy.sequence=v->sequence;out->legacy.update_state=v->update_state;out->legacy.image_base=v->image_base;out->legacy.image_size=v->image_size;out->legacy.image_crc32=v->image_crc32;memcpy(out->legacy.software_version,v->software_version,4U);}}
static ImageMetadata_StatusType Erase(uint32_t p){FLASH_EraseInitTypeDef e={0};uint32_t pe=0;HAL_StatusTypeDef h;if(!IsPage(p))return IMAGE_METADATA_INVALID_ARGUMENT;e.TypeErase=FLASH_TYPEERASE_PAGES;e.PageAddress=p;e.NbPages=1U;HAL_FLASH_Unlock();h=HAL_FLASHEx_Erase(&e,&pe);HAL_FLASH_Lock();DemEventAdapter_ReportFlashEraseResult(h==HAL_OK,HAL_GetTick());return h==HAL_OK?IMAGE_METADATA_OK:IMAGE_METADATA_ERASE_ERROR;}
static ImageMetadata_StatusType Program(uint32_t p,uint32_t o,const uint8_t*d,uint32_t n){uint32_t i;if(!IsPage(p)||!d||((o|n)&1U)||o+n>IMAGE_METADATA_PAGE_SIZE)return IMAGE_METADATA_INVALID_ARGUMENT;HAL_FLASH_Unlock();for(i=0;i<n;i+=2U){uint16_t hw=(uint16_t)d[i]|((uint16_t)d[i+1U]<<8U);uint32_t a=p+o+i;if(HAL_FLASH_Program(FLASH_TYPEPROGRAM_HALFWORD,a,hw)!=HAL_OK||*(volatile const uint16_t*)a!=hw){HAL_FLASH_Lock();DemEventAdapter_ReportFlashProgramResult(false,HAL_GetTick());return IMAGE_METADATA_PROGRAM_ERROR;}}HAL_FLASH_Lock();DemEventAdapter_ReportFlashProgramResult(true,HAL_GetTick());return IMAGE_METADATA_OK;}
ImageMetadata_StatusType ImageMetadata_CommitRecord(const ImageMetadata_RecordType*d){ImageMetadata_ScanResultType s;ImageMetadata_RecordType r,v;ImageMetadata_StatusType st;uint32_t target,previous;if(!d)return IMAGE_METADATA_INVALID_ARGUMENT;ImageMetadata_Scan(&s);r=*d;previous=s.state==IMAGE_METADATA_SCAN_V2_RECORD?s.record.sequence:s.state==IMAGE_METADATA_SCAN_V1_RECORD?s.legacy.sequence:0U;r.magic=IMAGE_METADATA_MAGIC;r.format_version=2U;r.record_size=64U;r.sequence=previous+1U;r.max_boot_attempts=3U;r.flags=0U;r.reserved16=0U;r.reserved32[0]=r.reserved32[1]=0U;r.commit_marker=0xFFFFU;r.padding=0xFFFFU;r.metadata_crc32=ImageValidator_CalculateCrc32((const uint8_t*)&r,56U);target=((s.state==IMAGE_METADATA_SCAN_V2_RECORD||s.state==IMAGE_METADATA_SCAN_V1_RECORD)&&s.active_page_address==IMAGE_METADATA_PAGE_A_ADDRESS)?IMAGE_METADATA_PAGE_B_ADDRESS:IMAGE_METADATA_PAGE_A_ADDRESS;st=Erase(target);if(st!=IMAGE_METADATA_OK)return st;st=Program(target,0U,(const uint8_t*)&r,60U);if(st!=IMAGE_METADATA_OK)return st;memcpy(&v,(const void*)target,64U);if(memcmp(&v,&r,60U)!=0)return IMAGE_METADATA_VERIFY_ERROR;{uint16_t m=IMAGE_METADATA_COMMIT_MARKER;st=Program(target,60U,(const uint8_t*)&m,2U);}if(st!=IMAGE_METADATA_OK)return st;memcpy(&v,(const void*)target,64U);return V2Valid(&v)?IMAGE_METADATA_OK:IMAGE_METADATA_VERIFY_ERROR;}
static void State(ImageMetadata_RecordType*r,uint8_t s,uint8_t st){if(s==IMAGE_SLOT_A_ID)r->slot_a_state=st;else r->slot_b_state=st;}
static void Image(ImageMetadata_RecordType*r,uint8_t s,uint32_t z,uint32_t c,const uint8_t*v){if(s==IMAGE_SLOT_A_ID){r->slot_a_image_size=z;r->slot_a_crc32=c;if(v)memcpy(r->slot_a_version,v,4U);}else{r->slot_b_image_size=z;r->slot_b_crc32=c;if(v)memcpy(r->slot_b_version,v,4U);}}
static bool Load(ImageMetadata_RecordType*r){ImageMetadata_ScanResultType s;ImageMetadata_Scan(&s);if(s.state!=IMAGE_METADATA_SCAN_V2_RECORD)return false;*r=s.record;return true;}
ImageMetadata_StatusType ImageMetadata_MigrateV1(const ImageMetadata_ScanResultType*s){ImageMetadata_RecordType r;if(!s||s->state!=IMAGE_METADATA_SCAN_V1_RECORD||s->legacy.update_state!=2U)return IMAGE_METADATA_INVALID_ARGUMENT;memset(&r,0,sizeof(r));Image(&r,IMAGE_SLOT_A_ID,s->legacy.image_size,s->legacy.image_crc32,s->legacy.software_version);r.slot_a_state=IMAGE_SLOT_STATE_CONFIRMED;r.slot_b_state=IMAGE_SLOT_STATE_EMPTY;r.active_slot=r.confirmed_slot=r.last_boot_slot=IMAGE_SLOT_A_ID;r.pending_slot=IMAGE_SLOT_NONE;r.rollback_reason=IMAGE_ROLLBACK_NONE;return ImageMetadata_CommitRecord(&r);}
ImageMetadata_StatusType ImageMetadata_MarkUpdateInProgress(uint8_t s,uint32_t z){ImageMetadata_RecordType r;if(!ImageLayout_IsSlotId(s)||!ImageValidator_IsImageRangeValidForSlot(s,ImageLayout_GetSlotBase(s),z))return IMAGE_METADATA_INVALID_ARGUMENT;if(!Load(&r)){ImageMetadata_ScanResultType scan;ImageMetadata_Scan(&scan);if(scan.state!=IMAGE_METADATA_ABSENT_LEGACY)return IMAGE_METADATA_INVALID_ARGUMENT;memset(&r,0,sizeof(r));r.slot_a_state=r.slot_b_state=IMAGE_SLOT_STATE_EMPTY;r.active_slot=r.confirmed_slot=r.pending_slot=r.last_boot_slot=IMAGE_SLOT_NONE;}if(s==r.confirmed_slot)return IMAGE_METADATA_INVALID_ARGUMENT;Image(&r,s,z,0U,NULL);State(&r,s,IMAGE_SLOT_STATE_UPDATE_IN_PROGRESS);r.pending_slot=IMAGE_SLOT_NONE;r.boot_attempt_count=0U;r.active_slot=r.confirmed_slot;return ImageMetadata_CommitRecord(&r);}
ImageMetadata_StatusType ImageMetadata_MarkPending(uint8_t s,uint32_t z,uint32_t c,const uint8_t*v){ImageMetadata_RecordType r;if(!ImageLayout_IsSlotId(s)||!v||!Load(&r)||ImageMetadata_GetSlotState(&r,s)!=IMAGE_SLOT_STATE_UPDATE_IN_PROGRESS)return IMAGE_METADATA_INVALID_ARGUMENT;Image(&r,s,z,c,v);State(&r,s,IMAGE_SLOT_STATE_PENDING);r.pending_slot=r.active_slot=s;r.boot_attempt_count=0U;return ImageMetadata_CommitRecord(&r);}
ImageMetadata_StatusType ImageMetadata_MarkCandidateInvalid(uint8_t s,ImageMetadata_RollbackReasonType why){ImageMetadata_RecordType r;if(!ImageLayout_IsSlotId(s)||why==IMAGE_ROLLBACK_NONE||why>IMAGE_ROLLBACK_CONFIRMED_IMAGE_INVALID||!Load(&r))return IMAGE_METADATA_INVALID_ARGUMENT;State(&r,s,IMAGE_SLOT_STATE_INVALID);if(r.pending_slot==s)r.pending_slot=IMAGE_SLOT_NONE;r.boot_attempt_count=0U;r.rollback_reason=(uint8_t)why;r.active_slot=r.confirmed_slot;return ImageMetadata_CommitRecord(&r);}
ImageMetadata_StatusType ImageMetadata_IncrementPendingAttempt(uint8_t s,ImageMetadata_RecordType*out){ImageMetadata_RecordType r;ImageMetadata_StatusType st;if(!Load(&r)||r.pending_slot!=s||r.boot_attempt_count>=3U)return IMAGE_METADATA_INVALID_ARGUMENT;r.boot_attempt_count++;r.last_boot_slot=r.active_slot=s;st=ImageMetadata_CommitRecord(&r);if(st==IMAGE_METADATA_OK&&out){ImageMetadata_ScanResultType n;ImageMetadata_Scan(&n);*out=n.record;}return st;}
ImageMetadata_StatusType ImageMetadata_ConfirmPending(uint8_t s,uint32_t seq){ImageMetadata_RecordType r;uint8_t old;if(!Load(&r)||r.sequence!=seq||r.pending_slot!=s||ImageMetadata_GetSlotState(&r,s)!=IMAGE_SLOT_STATE_PENDING)return IMAGE_METADATA_INVALID_ARGUMENT;old=r.confirmed_slot;if(ImageLayout_IsSlotId(old)&&old!=s)State(&r,old,IMAGE_SLOT_STATE_VALID_ROLLBACK);State(&r,s,IMAGE_SLOT_STATE_CONFIRMED);r.active_slot=r.confirmed_slot=r.last_boot_slot=s;r.pending_slot=IMAGE_SLOT_NONE;r.boot_attempt_count=0U;r.rollback_reason=IMAGE_ROLLBACK_NONE;return ImageMetadata_CommitRecord(&r);}
ImageMetadata_StatusType ImageMetadata_PromoteRollback(uint8_t bad,uint8_t fallback){ImageMetadata_RecordType r;if(!Load(&r)||r.confirmed_slot!=bad||ImageMetadata_GetSlotState(&r,fallback)!=IMAGE_SLOT_STATE_VALID_ROLLBACK)return IMAGE_METADATA_INVALID_ARGUMENT;State(&r,bad,IMAGE_SLOT_STATE_INVALID);State(&r,fallback,IMAGE_SLOT_STATE_CONFIRMED);r.active_slot=r.confirmed_slot=r.last_boot_slot=fallback;r.pending_slot=IMAGE_SLOT_NONE;r.boot_attempt_count=0U;r.rollback_reason=IMAGE_ROLLBACK_CONFIRMED_IMAGE_INVALID;return ImageMetadata_CommitRecord(&r);}
